connections:
  - readerid: "InputFile"
    writerid: "tcp1"
  - readerid: "tcp1"
    writerid: "ipc1"
  - readerid: "ipc1"
    writerid: "udp1"
  - readerid: "udp1"
    writerid: "OutputFile"
nodes:
  files:
    - id: "InputFile"
      path: "input.txt"
    - id: "OutputFile"
      path: "output.txt"
      trunc: true
  sockets:
    - id: "tcp1"
      protocol: "TCP"
      address: "127.0.0.1"
      port: 57132
    - id: "udp1"
      protocol: "UDP"
      address: "127.0.0.1"
      port: 63211
  ipcs:
    - id: "ipc1"
      channel: "ipc-channel1"
settings:
  timeout: 3
