name: CI Build

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23.4'
    
    - name: Build
      run: go build

    - name: Test
      run: go test -v ./...

    - name: Log Coverage and Commit Hash
      run: |
        echo "Coverage: ${{ steps.jacoco.outputs.coverage }}%"
        echo "Current Hash: $(git rev-parse HEAD)"

    - name: Update coverage badge
      uses: ncruces/go-coverage-report@main
